### PR TITLE
[GSoC] test data for scene text detection and recognition (High Level API)

### PR DESCRIPTION
**Pull request by HannibalAPE**
test data for https://github.com/opencv/opencv/pull/17570

### CODE REVIEW

**Comment by alalek** [comment]
> +130Mb

Not allowed.

Large files (models, >1Mb) for DNN should be stored on external resources (Google Drive, DropBox, OneDrive, etc).

Test images should be kept small (no need to store FullHD images in PNG format - 320x240 may be enough for regression test)

**Comment by HannibalAPE** [comment]
> > +130Mb
> 
> Not allowed.
> 
> Large files (models, >1Mb) for DNN should be stored on external resources (Google Drive, DropBox, OneDrive, etc).
> 
> Test images should be kept small (no need to store FullHD images in PNG format - 320x240 may be enough for regression test)

@alalek I have already uploaded the model weights to Google Drive:
1. crnn.onnx: https://drive.google.com/file/d/1ooaLR-rkTl8jdpGy1DoQs0-X0lQsB6Fj/view?usp=sharing
2. DB_IC15_resnet50.onnx: https://drive.google.com/file/d/1cmAs91yFRyC2LC3nTTBNNYooyEmb0i5t/view?usp=sharing
3. DB_TD500_resnet50.onnx: https://drive.google.com/file/d/1_9KB6QkIghp2VNZti_dJ3Araz-nDZBsL/view?usp=sharing

Then, I should resize the rest images, and only put the images to the new branch? How about the model weights?
Thanks in advance.

**Comment by alalek** [comment]
Put links on models weights into sample/documentation. So Users can download these files by using provided links.
In samples assume that these external files are located in the current folder.

For tests, see https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/download_models.py  (including this file history and related PRs). Use `cvtest::findDataFile()` with `required=False` (share on CI is updated manually, so files may missing)

**Comment by alalek** [comment]
Please squash commits to remove huge remove files from Git history.

**Comment by HannibalAPE** [comment]
> Please squash commits to remove huge remove files from Git history.
@alalek 
sorry, this is my first to pull a request, and I am not sure whether I successfully squash my commits.
If I make a mistake again, can I just close this pr, and open a new one?

**Comment by alalek** [comment]
> just close this

Do NOT do that. Just push your changes with "--force" option.

```
git reset --hard b9d7d2b83efe552b3eb43ea9311e1e53f01456dd
git push --force ...
```

**Comment by HannibalAPE** [comment]
@alalek Thank you for your help.

**Pull request merged**
