### PR TITLE
GSOC17 - Facemark API

### PR DESCRIPTION
**Pull request by kurnianggoro**
Project: API for Facial Landmark Detector
Mentor: Delia Passalacqua

This pull request contains the test data for the Facemark algorithms.
image source:
-mark.jpg: https://commons.wikimedia.org/wiki/File:Mark_Zuckerberg_em_setembro_de_2014.jpg
-therock.jpg: https://commons.wikimedia.org/wiki/File:Dwayne_The_Rock_Johnson_eyes_trees_2009_portrait.jpg

### CODE REVIEW

**Comment by alalek** [comment]
No need to reopen PRs - just push updates into your opencv_extra branch and then push updates (or dummy/amended commit) into opencv_contrib repo

**Comment by kurnianggoro** [comment]
@alalek sorry i could not understand, so basically no pull request and nothing to do in opencv_contrib repo? will it atomatically merged?

**Comment by alalek** [comment]
Pull requests from opencv_extra are not tested standalone. They should have "main" pull request - in your case, from opencv_contrib repository.
To trigger test builds with new code/data you should touch "main" opencv_contrib pull request  (opencv_contrib PR will pull updates from opencv_extra before tests run).

**Comment by kurnianggoro** [comment]
ok thank you @alalek, i think i understand how it works now. But, do you have any idea why the data here raise a warning in documentation building bot? I got warning message 
"stat" returned: (33206, 6042233, 64771, 1, 100000, 100000, 8120043, 1503683697, 1503683697, 1503683697)
File size: 8120043 bytes = 7929 KiB = 7 MiB
[see here](http://pullrequest.opencv.org/buildbot/builders/precommit-contrib_docs/builds/11091)
But i see there are several files in opencv_extra that bigger than my file.

**Comment by alalek** [comment]
We have policy about large files to prevent excessive growing of source code repository.
Large files / binary files / other data blobs should be stored outside of source code repository.

[More info](https://github.com/opencv/opencv_contrib/pull/1199#issuecomment-316030609)

**Comment by kurnianggoro** [comment]
@alalek my biggest file size is 800kB but i still got warning related to file size, so i guess i should just move that files to opencv_3rdparty repository and follows your example.
But i have another similar warning from opencv_contrib,
previously i have big file size but already deleted it. So, no more big file size from my opencv_contrib, only pure code (text file). Is this warning from another modules (i have not synced my repo with master) or another matter?  
Thanks in advance

**Comment by alalek** [comment]
There are more 100+ commits in opencv_contrib patch, so git tracks all changes and may keep in history removed files too.
Please squash commits into one via `git rebase -i HEAD~122` (or `upstream/master`) and `git push -f` (with force).

**Comment by kurnianggoro** [comment]
thanks, there is no more warning now.

**Pull request merged**
