### PR TITLE
Update ENet downloading link

### PR DESCRIPTION
**Pull request by dkurt**

### CODE REVIEW

**Comment by dkurt** [comment]
@mshabunin, @allnes, Please check this PR.

**Comment by allnes** [comment]
+1

**Comment by akineeic** [comment]
@dkurt Sorry to bother you. I'm wondering if you know the inference parameters for the updated model like input size, mean, std, etc. I tried the paramsters in the [models.yml](https://github.com/opencv/opencv/blob/master/samples/dnn/models.yml#L111-L119) in opencv, but the output as shown below doesn't look good visually.
Enet
For comparison, the output of FCN is shown below.
FCN

**Comment by dkurt** [comment]
@akineeic, ENet is ADAS scenario segmentation network. Please check the paper: https://arxiv.org/abs/1606.02147

**Comment by akineeic** [comment]
@dkurt Thanks for your quick reply. I'll check the paper to find the information.

**Pull request merged**
