### PR TITLE
onnx test model for Ceil, Floor, Log, Round, Sqrt layer and data added

### PR DESCRIPTION
**Pull request by ashishkrshrivastava**

### CODE REVIEW

**Comment by alalek** [comment]
Please rebase on latest 3.4 branch

**Comment by alalek** [comment]
In configured environment:
```
git fetch upstream
git rebase -i upstream/3.4
```

**Comment by ashishkrshrivastava** [comment]
@alalek, Thank you so much.

**Comment by ashishkrshrivastava** [comment]
Closing this PR as I find it unnecessary.

**Pull request closed without merging**
