### PR TITLE
add testdata for DataAugmentation with different sizes

### PR DESCRIPTION
**Pull request by zhaoyue-zephyrus**

### CODE REVIEW

**Comment by l-bat** [comment]
Please attach `prototxt` for tests

**Comment by l-bat** [comment]
Please attach `caffemodel` for tests

**Comment by zhaoyue-zephyrus** [comment]
Oops, `caffemodel` are ignored by unless using `-f`. Now fixed.

**Comment by l-bat** [comment]
Please look at this warning https://pullrequest.opencv.org/buildbot/builders/precommit_docs/builds/26251/steps/patch%20size%20opencv_extra/logs/stdio
What is the main difference between `data_augmentation_2x1 `and `data_augmentation_8x6 `models? Can we only add `data_augmentation_2x1 ` model to avoid  exceeding the memory limit?

**Comment by zhaoyue-zephyrus** [comment]
I use 2x1 and 8x6 to test that DataAug works for both enlarging (2x1 => 4x3) and shrinking (8x6 => 4x3). If I understand correctly, both model should have only hundreds of bytes?

**Comment by l-bat** [comment]
I'm sorry if I gave you the wrong idea. Please rebase your PR to 3.4 branch.

**Comment by dkurt** [comment]
Please change target branch to 3.4

**Pull request merged**
