### PR TITLE
adding results for ridge_filter for ref

### PR DESCRIPTION
**Pull request by VenkateshVijaykumar**

### CODE REVIEW

**Comment by sovrasov** [comment]
To reduce test data size you can use a fewer amount of images.

**Comment by kushalvyas** [comment]
@sovrasov , do I need to re-reference the #395 PR of opencv_extra ( which contains the extra data) again?

**Comment by alalek** [comment]
Git stores history, so just adding commits doesn't work to reduce size.
You need to squash your commits into one.
After updating data in this PR, you need to update (amend last commit) in opencv_contrib PR to re-trigger builds.

**Comment by kushalvyas** [comment]
thank you, will do that :)

**Pull request closed without merging**
