### PR TITLE
Test model and data for Scatter & ScatterND from ONNX

### PR DESCRIPTION
**Pull request by fengyuentau**
https://github.com/opencv/opencv/pull/22529

### CODE REVIEW

**Review by rogday — COMMENTED** [review]
Thank you!
I think we should update the commit link in `testdata/onnx/conformance/README.md`

**Comment by asmorkalov** [comment]
Also please squash commits in extra.

**Comment by fengyuentau** [comment]
> Thank you! I think we should update the commit link in `testdata/onnx/conformance/README.md`

This pr just updated scatter and scatternd related models and data. Should I add a new link instead?

**Comment by rogday** [comment]
> @rogday  This pr just updated scatter and scatternd related models and data. Should I add a new link instead?

If you did a partial update, you could add a new link for scatter instead of replacing the old one. The source of the data should be clear.

**Comment by fengyuentau** [comment]
> > @rogday  This pr just updated scatter and scatternd related models and data. Should I add a new link instead?
> 
> If you did a partial update, you could add a new link for scatter instead of replacing the old one. The source of the data should be clear.

Thank you! The commit link for scatter and scatternd has been added.

**Review by rogday — APPROVED** [review]
:+1:

**Pull request merged**
