### PR TITLE
Fuzzy module optimization - data

### PR DESCRIPTION
**Pull request by tucna**
Data for #884.

- Updated images.

### CODE REVIEW

**Comment by alalek** [comment]
Please remove unnecessary merge commits.

**Comment by tucna** [comment]
@alalek I am so sorry I have a hard time to fix it. Is there any quick solution?

**Comment by alalek** [comment]
I have rebased your patch.

To sync with GitHub execute commands like this:
```
# commit/stash your pending changes somewhere
# make backup
git branch fuzzy_optimization_backup fuzzy_optimization
git fetch https://github.com/tucna/opencv_extra fuzzy_optimization
git checkout -B fuzzy_optimization FETCH_HEAD
```

**Comment by tucna** [comment]
@alalek Thank you, great! Can I ask you if

`git rebase -i upstream/master`

this is correct way how to rebase?

**Comment by alalek** [comment]
Yes, it works great if there is no merge commits. To avoid merge commits use `git pull --rebase` (instead of simple `git pull`) and avoid `git merge` calls (use `git rebase -i upstream/master` instead of `git merge upstream/master`).

In this case I resolved conflict via `git checkout <patch sha> -- .` command (just get required changes without commits history).

**Pull request merged**
