### PR TITLE
add humanseg model and test data

### PR DESCRIPTION
**Pull request by wjj19950828**
test data and onnx model for PR:https://github.com/opencv/opencv/pull/20511

### CODE REVIEW

**Comment by fengyuentau** [comment]
Patch size is limited to 1024KiB. You can try follow [this example](https://github.com/opencv/opencv_extra/blob/3.4/testdata/dnn/onnx/generate_onnx_models.py) to generate an ONNX model with the single layer you want to test.

**Comment by wjj19950828** [comment]
Because my model is exported from Paddle to ONNX,but `generate_onnx_model.py` use PyTorch,so can i upload the ONNX model to Google Drive like this:https://github.com/opencv/opencv_extra/pull/773

**Comment by fengyuentau** [comment]
> Because my model is exported from Paddle to ONNX,but `generate_onnx_model.py` use PyTorch,so can i upload the ONNX model to Google Drive like this:#773

1. Your regression test is for the Resize layer, so please push an ONNX for test of this layer only. You can take a look at the script and other ONNX models, which all follow the same principle. Make an ONNX like this:
```shell
Input -> Resize -> Output
```
2. In cases like #773 , you can place the your GDrive URL in https://github.com/opencv/opencv_extra/blob/3.4/testdata/dnn/download_models.py like the following:
https://github.com/opencv/opencv_extra/blob/af569857801d989cc8b9d80a565b2ebeefe576cb/testdata/dnn/download_models.py#L842-L846

**Comment by wjj19950828** [comment]
> > Because my model is exported from Paddle to ONNX,but `generate_onnx_model.py` use PyTorch,so can i upload the ONNX model to Google Drive like this:#773
> 
> 1. Your regression test is for the Resize layer, so please push an ONNX for the test of this layer only. You can take a look at the script and other ONNX models, which all follow the same principle. Make an ONNX like this:
> 
> ```shell
> Input -> Resize -> Output
> ```
> 
> 1. In cases like [[GSoC] test data for scene text detection and recognition (High Level API) #773](https://github.com/opencv/opencv_extra/pull/773) , you can place the your GDrive URL in https://github.com/opencv/opencv_extra/blob/3.4/testdata/dnn/download_models.py like the following:
>    https://github.com/opencv/opencv_extra/blob/af569857801d989cc8b9d80a565b2ebeefe576cb/testdata/dnn/download_models.py#L842-L846

Thanks for your suggestions~

**Comment by alalek** [comment]
Need to squash commits into one to reduce size of git history.

**Comment by wjj19950828** [comment]
> Need to squash commits into one to reduce size of git history.

Thank you for your help~

**Pull request merged**
